### PR TITLE
Alpha-bug fixes

### LINKED ISSUE #182: Adding contacts with the same details except name.
Contacts were initially supposed to be differentiated by Name and Phone Number. This is because it is unlikely for two different people to have the same phone number.

### LINKED ISSUE #199: Edit Command able to edit from unshown contact list
To replicate the bug,

1. Do `list -e`
2. Do `edit 1 p/91234567`

Since contact list is not shown, index should not be referring to anything and edit should be disallowed.

### LINKED ISSUE #202: Log issue: Log shows "Initialize AddressBook" rather than DreamDayDesigner
When starting the app from the terminal as specified in the UG, the starting log message is "Initializing AddressBook" instead of the app name "DreamDayDesigner".

image

To Reproduce:
1. Start the app from the terminal as specified in the UG.
2. Observe the log message shown in the terminal

### LINKED ISSUE #215: Name with different casing are treated as different names
They should be handled in a way such that different casings should be regarded as the same `Name`

### PR DESCRIPTION
**Pull request by casperngeen**
- [X] `isSameContact` now checks for equality in `Phone` or `Name`, instead of just `Name`, therefore contacts must not have duplicate `Name` or `Phone`
- [X] Also updated the log message to show `Dream Day Designer` instead of `AddressBook`
- [X] Storage of `Name` has been updated to disregard casing of input
- [X] json file is now named `ddd.json` instead of `addressbook.json` to align with the UG
- [X] Edit command now checks if the items displayed on the Display are `Contacts` and will throw an error if the item retrieved from the display is not a `Contact`

Closes #182
Closes #199 
Closes #202
Closes #215

### CODE REVIEW

File: src/main/java/seedu/ddd/model/contact/common/Contact.java [hunk 1]
```diff
@@ -111,7 +111,7 @@ public void removeEvent(Event event) {
     }
 
     /**
-     * Returns true if both persons have the same name.
+     * Returns true if both persons have the same name and phone number.
```
Comment (leslieyip02) [inline src/main/java/seedu/ddd/model/contact/common/Contact.java:114]: Was this meant to be "or" instead of "and"?

**Review by leslieyip02 — APPROVED** [review]

File: src/main/java/seedu/ddd/model/contact/common/Contact.java (hunk 1 above)
Comment (Teddayz) [reply src/main/java/seedu/ddd/model/contact/common/Contact.java:114]: I think based on our previous conversation we decided "and".

File: src/main/java/seedu/ddd/model/contact/common/Contact.java [hunk 2]
```diff
@@ -120,7 +120,8 @@ public boolean isSameContact(Contact otherContact) {
         }
 
         return otherContact != null
-                && otherContact.getName().equals(getName());
+                && (otherContact.getName().isSameName(name)
+                || otherContact.getPhone().equals(phone));
```
Comment (Teddayz) [inline src/main/java/seedu/ddd/model/contact/common/Contact.java:124]: Should this be changed to && instead?

Comment (casperngeen) [reply src/main/java/seedu/ddd/model/contact/common/Contact.java:124]: If you use &&, same phone and different name or same name but different phone will be treated as different contact. But I thought if either one is the same, the contact should be considered to be the same?

File: src/main/java/seedu/ddd/model/contact/common/Contact.java (hunk 1 above)
Comment (casperngeen) [reply src/main/java/seedu/ddd/model/contact/common/Contact.java:114]: I think i implemented "or"
