### PR TITLE
Fixed bug related to `list` command

### LINKED ISSUE #205: `List` command allows filtering for fields it does not have.
To replicate the bug, type in `list -c s/catering` .
It will display the client list. However, there should be an error shown to the user as clients do not have services. 
Likewise, for events, we cannot filter by address, phone number, dtag, email etc.
Both clients and vendors should not be able to filter by description or date.

### PR DESCRIPTION
**Pull request by Teddayz**
Closes #205 and #198 

- [x] Made it such that PREFIX_SERVICE cannot be input into an input with flags `-e` and `-c`. As only a vendor contains a service.

- [x] Repeated it for the different cases for events, vendors, and clients. so that we cannot filter the list by fields that events don't have and vice versa. 
For example, `list -e a/Blk 123` previously would just list all events. Now it will throw an error to say that we cannot use the flag `a/` for event flags.

- [x] Update UserGuide
- [x] Refactored list test cases

### CODE REVIEW

File: src/main/java/seedu/ddd/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -223,4 +231,69 @@ public static CommandFlag parseFlags(ArgumentMultimap argMultimap) throws ParseE
...
+     * @throws ParseException if the ArgumentMultimap contains filters for description or date
+     *         when the vendor flag (-v) is specified.
+     */
+    public static void verifyVendorParser(ArgumentMultimap argMultimap) throws ParseException {
+        if (argMultimap.getValue(PREFIX_DESC).isPresent()) {
+            throw new ParseException(getErrorMessageForPrefix(PREFIX_DESC, FLAG_VENDOR));
+        } else if (argMultimap.getValue(PREFIX_DATE).isPresent()) {
+            throw new ParseException(getErrorMessageForPrefix(PREFIX_DATE, FLAG_VENDOR));
+        } else {
+
```
Comment (leslieyip02) [inline src/main/java/seedu/ddd/logic/parser/ParserUtil.java:271]: I think you can either leave a comment here or just omit the last `else` block instead of having an empty `else` block.

**Review by leslieyip02 — APPROVED** [review]

File: src/main/java/seedu/ddd/logic/parser/ParserUtil.java (hunk 1 above)
Comment (Teddayz) [reply src/main/java/seedu/ddd/logic/parser/ParserUtil.java]: Updated with a comment. If I omit the last `else` block, it will fail the checkstyle script.
